#general Documentation https://game.ci/docs/github/builder

name: Generate Build

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildAndTestForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ./
        unityVersion:
          - 2021.3.9f1
        targetPlatform:
          - StandaloneWindows64
          #- StandaloneOSX
          #- StandaloneLinux64
    steps:
      - uses: actions/checkout@v2.6.0
        with:
          lfs: true
      - uses: actions/cache@v3.0.11
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: webbertakken/unity-builder@v2.1.2
        with:
          buildName: ${{ github.head_ref }}
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
